### PR TITLE
Bump mathlib and Lean

### PR DESCRIPTION
**Pull request by PatrickMassot**
WIP bump

### CODE REVIEW

**Comment by hrmacbeth** [comment]
Thank you, I will incorporate this at the next major update (probably in a month).

**Comment by maverick-harmonic** [comment]
Thanks! I actually ran into this same issue when incorporating it into a project with a newer mathlib.

**Comment by hrmacbeth** [comment]
@maverick-harmonic Can you say more about your use case?  I am glad, but a little surprised, that there is something in the book (as opposed to in mathlib itself) which you want to rely on externally.

**Comment by maverick-harmonic** [comment]
This isn’t a typical use case. I didn’t have internet to download mathlib
into your repo so I cloned it into a scratch repo I had that already had
mathlib built. So all good 😊

**Comment by hrmacbeth** [comment]
Bumped to latest mathlib in fe7386009629bc00a1bcc89065db2db305b0ab63

**Pull request closed without merging**
